Improve InfluxDB data
mconcas/plancton pull request #103
Opened 2016-12-08 23:39 UTC by mconcas

WARNING: before pushing this to the `hlt` repository, I suggest to reset current database. 

 - Change the name of the metrics `measurements -> host`
 - Add number of running containers in the `"daemon"` tag

2016-12-09 16:13 UTC, dberzano commented on plancton/__init__.py
> +    self.streamer(series="host",
Do not change the series name.

2016-12-09 16:13 UTC, dberzano commented on plancton/__init__.py
> +                  fields={ "containers": running })
It's better if you push `containers` into the `measurements` series. You will use one HTTP request only.

2016-12-09 16:20 UTC, mconcas commented on plancton/__init__.py
> +                  fields={ "containers": running })
In such a way it would not be possible to show the number of running containers alongside the other daemon-related data

2016-12-09 16:21 UTC, mconcas commented on plancton/__init__.py
> +    self.streamer(series="host",
(y)

2016-12-09 20:00 UTC, dberzano requested changes

2016-12-09 20:00 UTC, dberzano commented on plancton/__init__.py
> +                  fields={ "containers": running })
You have a point. Would it be possible then to send it _once_, at lines 456-458, along with the rest of the information?

2016-12-09 23:41 UTC, mconcas commented on plancton/__init__.py
> +                  fields={ "containers": running })
Yes, I did the opposite, since `running` was evaluated after sending the first message.

2016-12-09 23:43 UTC, dberzano requested changes

2016-12-09 23:43 UTC, dberzano commented on plancton/__init__.py
> +                           "status": "draining" if draining else "active"})
You miss an extra space after `"active"`

2016-12-10 00:14 UTC, dberzano approved these changes

2016-12-10 00:19 UTC, merged